[package]
name = "maki-pack"
version.workspace = true
edition.workspace = true

[dependencies]
maki-storage = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smol = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
test-case = { workspace = true }
