[package]
name = "maki-interpreter"
version.workspace = true
edition.workspace = true

[dependencies]
monty = { workspace = true }
monty-types = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
